ContactUs/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from .views import emailView, successView

urlpatterns = [
    path('', emailView, name='email'),
    path('success/', successView, name='success'),
]

contactus/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from .views import emailView, successView

app_name = 'contactus'
urlpatterns = [
    path('', emailView, name='email'),
    path('success/', successView, name='success'),
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.views.generic import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',TemplateView.as_view(template_name='home/index.html'),name='home'),
    path('sponsor/',include('sponsor.urls')),
    path('contact-us/', include('contactus.urls')),
]

sponsor/urls.py
from django.urls import path
from . import views

app_name = 'sponsor'
urlpatterns = [
    path('',views.sponsor,name='sponsor'),
 
]

contactus/models.py
from django.db import models

# Create your models here.

sponsor/models.py
from django.db import models

# Create your models here.
class Sponsor_info(models.Model):	
	name = models.CharField(max_length=30)
	email = models.EmailField(max_length=30)
	contact_no = models.IntegerField(max_length=12)
	description = models.TextField(max_length=200)
	

contactus/forms.py
from django import forms

class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

sponsor/forms.py
from django import forms
from .models import Sponsor_info

class SponsorForm(forms.ModelForm):
	class Meta:
		model = Sponsor_info
		fields = '__all__'
	

ContactUs/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import ContactForm

def emailView(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['admin@example.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('success')
    return render(request, "home/index.html", {'form': form})

def successView(request):
    return HttpResponse('Success! Thank you for your message.')

contactus/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import ContactForm

def emailView(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['riyabansal261198@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect(reverse('contactus:success'))
    return render(request, "contact-us.html", {'form': form})

def successView(request):
    return render(request, "home/index.html")

sponsor/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Sponsor_info
from django.urls import reverse
from .forms import SponsorForm

# Create your views here.
def sponsor(request):
	if request.method == "POST":
		form = SponsorForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect(reverse('home'))
	else:	
		form = SponsorForm()
	return render(request,'home/sponsor.html',{'form':form})

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no, minimal-ui"/>
    <link href="{% static '/css/bootstrap.min.css' %}"  rel="stylesheet" type="text/css" />
    <link href="{% static '/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static '/css/idangerous.swiper.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static '/css/style.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static '/css/style1.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static '/css/style2.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static '/css/landing.css' %}" rel="stylesheet" type="text/css" />
    <title>JAZBAA Hackathon1.0</title>
  
</head>
<body data-color="yellow">

   {% block content %}

   {% endblock %}                        
    <!-- FOOTER -->
    <footer class="footer">
      <div class="container">
        <img class="f-logo" src="" alt="JAZBAA Hackathon1.0" style="color:white;">
      </div>
    </footer>  

    <script src="{% static '/js/jquery-2.1.4.min.js' %}"></script>
    <script src="{% static '/js/idangerous.swiper.min.js' %}"></script>
    <script src="{% static '/js/landing.js' %}"></script>
    <script src="{% static '/js/anchors.navigation.js' %}"></script>    
</body>

</html>

templates/contact-us.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block content %}
  
 <!-- HEADER -->
    <header class="header type-1">
      <div class="container">
        
      <nav class="main-nav">
                <ul class="anchor-navigation">
                    <li class="active"><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'home' %}">About-Us</a></li>
                    <li><a href="{% url 'home' %}">Our-Mission</a></li>
                    <li><a href="{% url 'home' %}">Our-Partners</a></li>
                    <li><a href="{% url 'home' %}">Register For Event</a></li>
                    <li><a href="{% url 'home' %}">FAQs</a></li>
                    <li><a href="{% url 'contactus:email' %}">Contact-Us</a></li>
                    
                </ul>       
      </nav>
            <button class="cmn-toggle-switch"><span></span></button>
      </div>
    </header>

<div id="content-wrapper">
    <div class="main-slider clearfix">
        <div class="main-block style-2" style="height:600px;">
            <img class="center-image" src="{% static '/img/bg_11.JPG' %}" alt="" >
                <div class="vertical-align">
                  <div class="container">
                    <div class="banner-block style-4">
		                <h4 class="banner-date animate delay-1">Jazbaa Hackathon1.0 </h4>
		                <h2 class="banner-title animate delay-2">Contact-Us</h2>
		            </div>
                  </div>
                </div> 
        </div>
    </div>
</div>
<div class="row" style="margin: 0; background: #f0f0f0;">
<div class="col-md-7" style="margin:100px;padding:20px;font-size:20px;border-radius:10px;width:60%;font-family:sans-serif;">

    <form method="post">
        {% csrf_token %}
            {{ form|crispy }}
                <div class="form-actions">
                    <button type="submit" id="SubmitForm">Send</button>
                </div>
    </form>    
</div>      
<div class="col-md-5" style="width:20%;font-size:20px;font-family:sans-serif;"><br><br><br><br><br><br>   

			<p><a href="www.lwindia.com">www.lwindia.com</a></p><br>
            <p>Contact:</p>
			<p><span>Mobile: </span> +91 9829105960 / 9351009002</p>
            <p><span>Phone: </span>0141-2501609</p><br>
		    <h2> @JAZBAA_hackathon1.0 </h2><br>

       
            
            

           
</div>

</div>
{% endblock %}

templates/home/sponsor.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block content %}
 
 <!-- HEADER -->
    <header class="header type-1">
      <div class="container">
        
      <nav class="main-nav">
                 <ul class="anchor-navigation">
                    <li class="active"><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'home' %}">About-Us</a></li>
                    <li><a href="{% url 'home' %}">Our-Mission</a></li>
                    <li><a href="{% url 'home' %}">Our-Partners</a></li>
                    <li><a href="{% url 'home' %}">Register For Event</a></li>
                    <li><a href="{% url 'home' %}">FAQs</a></li>
                    <li><a href="{% url 'contactus:email' %}">Contact-Us</a></li>
                    
                </ul>         
      </nav>
            <button class="cmn-toggle-switch"><span></span></button>
      </div>
    </header>

<div id="content-wrapper">
    <div class="main-slider clearfix">
        <div class="main-block style-2" style="height:600px;">
            <img class="center-image" src="{% static '/img/bg_11.JPG' %}" alt="" >
                <div class="vertical-align">
                  <div class="container">
                    <div class="banner-block style-4">
		                <h4 class="banner-date animate delay-1">Jazbaa Hackathon1.0 </h4>
		                <h2 class="banner-title animate delay-2">Register-Now</h2>
		            </div>
                  </div>
                </div> 
        </div>
    </div>
</div>
<div class="row" style="margin: 0; background: #f0f0f0;">
 <div style="margin:100px;padding:20px;font-size:20px;border-radius:10px;font-family:sans-serif;">

  					<form method="post" class="form">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="form-actions">
                          <button type="submit" id="FormSubmit">Submit</button>
                        </div>
                    </form>            

</div>                 
</div>

</div>
{% endblock %}